# Generated by Django 4.2.1 on 2023-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("THIN", "Худой"),
                    ("AVERAGE", "Средний"),
                    ("FIT", "Упитанный"),
                    ("MUSCULAR", "Мускулистый"),
                ],
                default="AVERAGE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("HIGH SCHOOL", "Среднее"),
                    ("COLLEGE", "Среднее профессиональное"),
                    ("PHD / POST DOCTORAL", "Высшее"),
                ],
                default="HIGH SCHOOL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("WHITE", "Белый"),
                    ("ASIAN", "Азиат"),
                    ("BLACK", "Негр"),
                    ("MIXED", "Мулат"),
                    ("OTHER ETHNICITY", "Иное"),
                ],
                default="WHITE",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Мужчина"), ("FEMALE", "Женщина")],
                default="MALE",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_colour",
            field=models.CharField(
                choices=[
                    ("BLACK", "Брюнет"),
                    ("BLONDE", "Блондин"),
                    ("BROWN", "Шатен"),
                    ("RED", "Рыжий"),
                    ("GREY", "Седой"),
                    ("FAIR", "Русый"),
                    ("OTHER", "Другое"),
                ],
                default="BLACK",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_length",
            field=models.CharField(
                choices=[
                    ("LONG", "Длинные"),
                    ("SHOULDER LENGTH", "Каре"),
                    ("AVERAGE", "Средние"),
                    ("SHORT", "Короткие"),
                    ("SHAVED", "Лысый"),
                ],
                default="LONG",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="looking_for",
            field=models.CharField(
                choices=[("MALE", "Мужчина"), ("FEMALE", "Женщина")],
                default="BOTH",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="relationship_status",
            field=models.CharField(
                choices=[
                    ("NEVER MARRIED", "Не женат"),
                    ("DIVORCED", "Разведен"),
                    ("WIDOWED", "Вдовец"),
                ],
                default="NEVER MARRIED",
                max_length=100,
            ),
        ),
    ]
