# Generated by Django 4.2.1 on 2023-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hair_colour",
            field=models.CharField(
                choices=[
                    ("БРЮНЕТ", "Брюнет"),
                    ("BLONDE", "Блондин"),
                    ("BROWN", "Шатен"),
                    ("RED", "Рыжий"),
                    ("GREY", "Седой"),
                    ("FAIR", "Русый"),
                    ("OTHER", "Другое"),
                ],
                default="BLACK",
                max_length=10,
            ),
        ),
    ]
