# Generated by Django 4.2.1 on 2023-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_remove_profile_citylat_remove_profile_citylong_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("HIGH SCHOOL", "Среднее"),
                    ("COLLEGE", "Среднее профессиональное"),
                    ("UNIVERSATY", "Высшее"),
                ],
                default="HIGH SCHOOL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="looking_for",
            field=models.CharField(
                choices=[("Мужчина", "Мужчина"), ("Женщина", "Женщина")],
                default="Мужчина",
                max_length=7,
            ),
        ),
    ]
