# Generated by Django 4.2.1 on 2023-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_education_alter_profile_looking_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("Худой", "Худой"),
                    ("Средний", "Средний"),
                    ("Упитанный", "Упитанный"),
                    ("Мускулистый", "Мускулистый"),
                ],
                default="Худой",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="children",
            field=models.BooleanField(default="Нет"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("Среднее", "Среднее"),
                    ("Среднее профессиональное", "Среднее профессиональное"),
                    ("Высшее", "Высшее"),
                ],
                default="Среднее",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("Белый", "Белый"),
                    ("Азиат", "Азиат"),
                    ("Негр", "Негр"),
                    ("Метис", "Метис"),
                    ("Иное", "Иное"),
                ],
                default="Белый",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Мужчина", "Мужчина"), ("Женщина", "Женщина")],
                default="Мужчина",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_colour",
            field=models.CharField(
                choices=[
                    ("Брюнет", "Брюнет"),
                    ("Блондин", "Блондин"),
                    ("Шатен", "Шатен"),
                    ("Рыжий", "Рыжий"),
                    ("Седой", "Седой"),
                    ("Русый", "Русый"),
                    ("Другое", "Другое"),
                ],
                default="Брюнет",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_length",
            field=models.CharField(
                choices=[
                    ("Длинные", "Длинные"),
                    ("Каре", "Каре"),
                    ("Средние", "Средние"),
                    ("Короткие", "Короткие"),
                    ("Лысый", "Лысый"),
                ],
                default="Длинные",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="relationship_status",
            field=models.CharField(
                choices=[
                    ("Не женат", "Не женат"),
                    ("Разведен", "Разведен"),
                    ("Вдовец", "Вдовец"),
                ],
                default="Не женат",
                max_length=100,
            ),
        ),
    ]
