# Generated by Django 4.2.1 on 2023-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_profile_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("THIN", "Thin"),
                    ("AVERAGE", "Average"),
                    ("FIT", "Fit"),
                    ("MUSCULAR", "Muscular"),
                    ("A LITTLE EXTRA", "A Little Extra"),
                    ("CURVY", "Curvy"),
                ],
                default="Худой",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("HIGH SCHOOL", "High School"),
                    ("COLLEGE", "College"),
                    ("BACHELORS DEGREE", "Bachelors Degree"),
                    ("MASTERS", "Masters"),
                    ("PHD / POST DOCTORAL", "PhD / Post Doctoral"),
                ],
                default="Среднее",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("WHITE", "White"),
                    ("ASIAN: INDIAN", "Asian: Indian"),
                    ("ASIAN: PAKISTANI", "Asian: Pakistani"),
                    ("ASIAN: BANGLADESHI", "Asian: Bangladeshi"),
                    ("ASIAN: CHINESE", "Asian: Chinese"),
                    ("BLACK", "Black"),
                    ("MIXED", "Mixed"),
                    ("OTHER ETHNICITY", "Other Ethnicity"),
                ],
                default="Белый",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="Мужчина",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_colour",
            field=models.CharField(
                choices=[
                    ("BLACK", "Black"),
                    ("BLONDE", "Blonde"),
                    ("BROWN", "Brown"),
                    ("RED", "Red"),
                    ("GREY", "Grey"),
                    ("BALD", "Bald"),
                    ("BLUE", "Blue"),
                    ("PINK", "Pink"),
                    ("GREEN", "Green"),
                    ("PURPLE", "Purple"),
                    ("OTHER", "Other"),
                ],
                default="Брюнет",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_length",
            field=models.CharField(
                choices=[
                    ("LONG", "Long"),
                    ("SHOULDER LENGTH", "Shoulder Length"),
                    ("AVERAGE", "Average"),
                    ("SHORT", "Short"),
                    ("SHAVED", "Shaved"),
                ],
                default="Длинные",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="looking_for",
            field=models.CharField(
                choices=[("MALE", "Men"), ("FEMALE", "Women"), ("BOTH", "Both")],
                default="Мужчина",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="relationship_status",
            field=models.CharField(
                choices=[
                    ("NEVER MARRIED", "Never Married"),
                    ("DIVORCED", "Divorced"),
                    ("WIDOWED", "Widowed"),
                    ("SEPARATED", "Separated"),
                ],
                default="Не женат",
                max_length=100,
            ),
        ),
    ]
