# Generated by Django 4.2.1 on 2023-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_profile_body_type_alter_profile_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="looking_for",
            field=models.CharField(
                choices=[("MALE", "Men"), ("FEMALE", "Women")],
                default="Мужчина",
                max_length=7,
            ),
        ),
    ]
